### ISSUE TITLE
web可以mp报错如下

### ISSUE THREAD

**Issue by zdwork** [Tencent/kbone#332]
ReferenceError: items is not defined
    at Object.lotteryZoom (other.js:1)
    at new w (other.js:1)
    at a.mounted (other.js:1)
    at Kt (vendors~home~other.js:2)
    at rn (vendors~home~other.js:2)
    at Object.insert (vendors~home~other.js:2)
    at k (vendors~home~other.js:2)
    at On.__patch__ (vendors~home~other.js:2)
    at On.t._update (vendors~home~other.js:2)
    at On.r (vendors~home~other.js:2)
Wt @ vendors~home~other.js:2
Jt @ vendors~home~other.js:2
Gt @ vendors~home~other.js:2
Kt @ vendors~home~other.js:2
rn @ vendors~home~other.js:2
insert @ vendors~home~other.js:2
k @ vendors~home~other.js:2
(anonymous) @ vendors~home~other.js:2
t._update @ vendors~home~other.js:2
r @ vendors~home~other.js:2
mn.get @ vendors~home~other.js:2
mn @ vendors~home~other.js:2
(anonymous) @ vendors~home~other.js:2
On.$mount @ vendors~home~other.js:2
On.$mount @ vendors~home~other.js:2
t._init @ vendors~home~other.js:2
On @ vendors~home~other.js:2
I @ other.js:1
onLoad @ base.js:192
(anonymous) @ VM214 WAService.js:2
p.__callPageLifeTime__ @ VM214 WAService.js:2
Dt @ VM214 WAService.js:2
Mt @ VM214 WAService.js:2
(anonymous) @ VM214 WAService.js:2
(anonymous) @ VM214 WAService.js:2
i.emit @ VM214 WAService.js:2
emit @ VM214 WAService.js:2
(anonymous) @ VM214 WAService.js:2
i.emit @ VM214 WAService.js:2
emit @ VM214 WAService.js:2
(anonymous) @ VM214 WAService.js:2
(anonymous) @ VM214 WAService.js:2
c @ VM212 asdebug.js:1
l @ VM212 asdebug.js:1
(anonymous) @ VM212 asdebug.js:1
f @ VM212 asdebug.js:1
p @ VM212 asdebug.js:1
(anonymous) @ VM212 asdebug.js:1
_ws.onmessage @ VM212 asdebug.js:1
Show 9 more frames

**Comment by JuneAndGreen** [comment]
这个看起来是业务代码里的报错，你可以把压缩混淆去掉看看能不能找到具体出错位置？

如果还是定位不了，可以给下 demo 我来看看。

**Comment by zdwork** [comment]
您好我是引用的这段代码  web是没问题，您那能帮试下小程序的吗
https://tgideas.qq.com/doc/frontend/component/common/lottery.html#%E5%9C%86%E5%BD%A2%E6%8A%BD%E5%A5%96%E4%BB%A3%E7%A0%81%E7%A4%BA%E4%BE%8B

**Comment by zdwork** [comment]
https://github.com/Venler/vue-lottery#readme  这个组件也不行，h5 正常 小程序空白页

**Comment by JuneAndGreen** [comment]
可以的话，建议把你那边出问题的小程序代码脱敏后直接给到我，这样定位问题的效率会高一些。

**Comment by zdwork** [comment]
非常感谢 已发送wx-miniprogram@qq.com 邮箱。

**Comment by JuneAndGreen** [comment]
> https://github.com/Venler/vue-lottery#readme 这个组件也不行，h5 正常 小程序空白页

空白是因为小程序的编译入口你没有加 vue.use(lottery) 。

不过这里直接用也有问题，vue-lottery 用了 scoped style，这个在 qa 有提到，因为小程序不支持动态 setAttribute，所以没法支持 scoped style。但是你可以手动把样式加到自己页面中：

```css
.lottery_wraper{
    position: relative;
    max-width: 500px;
}
.lottery_wraper img{
    width: 100%;
}
.lottery_Content{
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%,-50%);
    -webkit-transform: translate(-50%,-50%);
}
.lottery_pointer{
    position: absolute;
    top: 48%;
    left: 50%;
    transform: translate(-50%,-50%);
    -webkit-transform: translate(-50%,-50%);
}
```

同时 mp-webpack-plugin 更新到 1.2.0 （补了下 img {height: auto}，如果不想升级自己补下这个样式调整下就好，小程序默认的 image 组件是带高度的，得用这个样式干掉）。
