### ISSUE TITLE
如何迁移已有的vue ui组件

### ISSUE THREAD

**Issue by liudonghua123** [Tencent/kbone#333]
如果已有一个vue标准的web或mobile的ui组件、库，需要怎么修改或重写以便能用于kbone。例如我看到一个非常漂亮的vuesax ( https://github.com/lusaxweb/vuesax )，我想使用在小程序里面；另外其他一些桌面vue ui，例如 antd-vue ( https://github.com/vueComponent/ant-design-vue )，element ( https://github.com/ElemeFE/element ) 等，这些ui框架怎么以最小代价、最大复用迁移到能在kbone中使用。
我知道小程序中支持的web开发有限，但没有找到一些文档或资料如何迁移已有的vue ui。

**Comment by JuneAndGreen** [comment]
这个命题有点大，得简单做个分类：

首先纯逻辑类的组件，比较常见的那些基本上都是可以拿来使用的，像 vue router 那些，所以问题主要是那些 ui 组件。ui 组件库中我这边有尝试过一些，大部分 ui 库都会存在一些无法迁移的组件，无法迁移的原因主要在于：

1、使用了 getComputedStyle 或者 getBoundingClientRect 等接口，这些接口在小程序端暂时无法兼容成同步接口，所以不行；
2、使用了小程序无法支持的某种 scoped style 方案，这种只能手动将样式移到全局了；
3、依赖了一些 Web 端比较特殊的接口，比如富文本编辑器可能会以来的 contenteditable 属性；
4、使用了小程序不支持的样式、选择器，比如 input[type=checkbox]:checked 之类的。

基于这些原因，有些组件完全不支持，有些组件部分功能不支持。但又因为开源的 ui 库的数量很多，而其实现方案各不相同，所以很难给出一套完备的方案，只能开发者独自尝试是否符合自己需求。

而 kbone 这边会尝试提供一套和小程序组件风格一致的 ui 组件库，叫 kbone-ui，支持同时在 Web 端和小程序端运行，其中 1.0 版本是基于 vue 开发的，支持部分组件的跨端通用。目前 kbone-ui 的 2.0 版本正在开发中，将大部分可移植的小程序组件移植到 Web 端，可尝试一下 kbone-ui （kbone-ui 2.0 会基于 Web Component 来实现，所以相比 1.0 有更广的扩展性，预计近期会发 beta 版）。

如果是自己开发的 ui 组件的话，迁移需要主要下该特性是否能够在小程序端模拟出来，这里文档有简单的[开发建议](https://wechat-miniprogram.github.io/kbone/docs/guide/suggest.html)和之前已经踩过坑的[QA](https://wechat-miniprogram.github.io/kbone/docs/qa/#%E7%AD%94%E7%96%91)供参考。

**Comment by liudonghua123** [comment]
谢谢，get到了新东西 getComputedStyle ( https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle ), getBoundingClientRect ( https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect ), 我想使用的vuesax，以上三条基本都满足，最后一条可能不满足，可能会用到 input[type=checkbox]:checked 选择器设置一些动画效果，小程序以后能不能支持完整的web，毕竟小程序底层技术是源于web的，这方面有没有什么计划？

**Comment by JuneAndGreen** [comment]
目前看比较困难，因为小程序底层的实现是拆分成视图层和逻辑层两块，目前主要的不兼容都是因为这个架构导致的。不过部分不兼容我们也有在考虑（比如同步的 getComputedStyle 接口之类的），只是希望能在不影响目前主逻辑的情况下实现，所以推进也不会很快。

另外有一些不能直接兼容，但是有其他的方式来间接兼容，比如像 input[type=checkbox] 这个，底层会转而使用小程序的 checkbox 组件，所以可以通过外部修改 checkbox 组件的样式来间接实现 :checked 选择器的效果。

**Comment by liudonghua123** [comment]
微信小程序的 input[type=checkbox]:checked 可以使用如下方式实现，真正有用的是 `.weui-cells_checkbox[aria-checked="true"] + .weui-icon-checked`.

1. index.wxml

```xml
<checkbox-group bindchange="checkboxChange">
  <label wx:for="{{items}}">
    <checkbox value="{{item.name}}" checked="{{item.checked}}" color="red" class="weui-cells_checkbox" />
    <text class="weui-icon-checked"></text>
    <text>{{item.value}}</text>
  </label>
</checkbox-group>
```

2. index.wxss:

```css

[class^="weui-icon-checked"], [class*=" weui-icon-checked"] {
  display: inline-block;
  vertical-align: middle;
  width: 24px;
  height: 24px;
  -webkit-mask-position: 50% 50%;
  mask-position: 50% 50%;
  -webkit-mask-repeat: no-repeat;
  mask-repeat: no-repeat;
  -webkit-mask-size: 100%;
  mask-size: 100%;
  background-color: currentColor;
}

.weui-cells_checkbox {
  position: absolute;
  left: -9999px;
}

.weui-cells_checkbox + .weui-icon-checked {
  color: rgba(0, 0, 0, 0.3);
  -webkit-mask-image: url(data:image/svg+xml,%3Csvg%20width%3D%221000%22%20height%3D%221000%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20d%3D%22M500%20916.667C269.881%20916.667%2083.333%20730.119%2083.333%20500%2083.333%20269.881%20269.881%2083.333%20500%2083.333c230.119%200%20416.667%20186.548%20416.667%20416.667%200%20230.119-186.548%20416.667-416.667%20416.667zm0-50c202.504%200%20366.667-164.163%20366.667-366.667%200-202.504-164.163-366.667-366.667-366.667-202.504%200-366.667%20164.163-366.667%20366.667%200%20202.504%20164.163%20366.667%20366.667%20366.667z%22%20fill-rule%3D%22evenodd%22%20fill-opacity%3D%22.9%22%2F%3E%3C%2Fsvg%3E);
  mask-image: url(data:image/svg+xml,%3Csvg%20width%3D%221000%22%20height%3D%221000%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20d%3D%22M500%20916.667C269.881%20916.667%2083.333%20730.119%2083.333%20500%2083.333%20269.881%20269.881%2083.333%20500%2083.333c230.119%200%20416.667%20186.548%20416.667%20416.667%200%20230.119-186.548%20416.667-416.667%20416.667zm0-50c202.504%200%20366.667-164.163%20366.667-366.667%200-202.504-164.163-366.667-366.667-366.667-202.504%200-366.667%20164.163-366.667%20366.667%200%20202.504%20164.163%20366.667%20366.667%20366.667z%22%20fill-rule%3D%22evenodd%22%20fill-opacity%3D%22.9%22%2F%3E%3C%2Fsvg%3E);
}

.weui-cells_checkbox:checked + .weui-icon-checked,
.weui-cells_checkbox[aria-checked="true"] + .weui-icon-checked {
  color:green;
  -webkit-mask-image: url(data:image/svg+xml,%3Csvg%20width%3D%2224%22%20height%3D%2224%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20d%3D%22M12%2022C6.477%2022%202%2017.523%202%2012S6.477%202%2012%202s10%204.477%2010%2010-4.477%2010-10%2010zm-1.177-7.86l-2.765-2.767L7%2012.431l3.119%203.121a1%201%200%20001.414%200l5.952-5.95-1.062-1.062-5.6%205.6z%22%2F%3E%3C%2Fsvg%3E);
  mask-image: url(data:image/svg+xml,%3Csvg%20width%3D%2224%22%20height%3D%2224%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20d%3D%22M12%2022C6.477%2022%202%2017.523%202%2012S6.477%202%2012%202s10%204.477%2010%2010-4.477%2010-10%2010zm-1.177-7.86l-2.765-2.767L7%2012.431l3.119%203.121a1%201%200%20001.414%200l5.952-5.95-1.062-1.062-5.6%205.6z%22%2F%3E%3C%2Fsvg%3E);
}
```

通过这种方式就可以实现 input[type=checkbox]:checked 选择器设置一些动画效果
